const colors = {
  light: {
    text: "#1A1035",
    tint: "#7C3AED",
    background: "#F8F7FF",
    foreground: "#1A1035",
    card: "#FFFFFF",
    cardForeground: "#1A1035",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#EDE9FE",
    secondaryForeground: "#5B21B6",
    muted: "#F3F0FF",
    mutedForeground: "#9CA3AF",
    accent: "#EDE9FE",
    accentForeground: "#5B21B6",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#EDE9FE",
    input: "#F3F0FF",
    success: "#10B981",
    warning: "#F59E0B",
    cardMint: "#DCFCE7",
    cardYellow: "#FEF9C3",
    cardPurple: "#EDE9FE",
    cardBlue: "#DBEAFE",
    cardPink: "#FCE7F3",
    cardOrange: "#FFEDD5",
  },
  dark: {
    text: "#F5F3FF",
    tint: "#A78BFA",
    background: "#0D0A1E",
    foreground: "#F0ECFF",
    card: "#1C1740",
    cardForeground: "#F0ECFF",
    primary: "#8B5CF6",
    primaryForeground: "#FFFFFF",
    secondary: "#2D1F5E",
    secondaryForeground: "#C4B5FD",
    muted: "#261E4A",
    mutedForeground: "#8B83B0",
    accent: "#2D1F5E",
    accentForeground: "#C4B5FD",
    destructive: "#F87171",
    destructiveForeground: "#FFFFFF",
    border: "#3A3068",
    input: "#291F53",
    success: "#34D399",
    warning: "#FCD34D",
    cardMint: "#064E3B",
    cardYellow: "#451A03",
    cardPurple: "#2D1F5E",
    cardBlue: "#1E3A5F",
    cardPink: "#4A0E29",
    cardOrange: "#431407",
  },
  radius: 18,
};

export default colors;
